### ISSUE TITLE
Proposal: new Contract Schema for 0.4.0

### ISSUE THREAD

**Issue by maxlinc** [thoughtworks/pacto#113]
We've already talked about a bunch of new features, and have talked about the contract changes that they would require. I think I have a good enough idea of the changes required that it makes sense to put a proposal here rather than dealing with it separately through each PR.

Ideally the items under **breaking changes** should still load contracts that use the old format, but will display a deprecation warning.

The **additions** are non-breaking as long as they have a default value or handler.
### Breaking changes
- [ ] Rename path to uriTemplate (WebMock 0.18.0 has URI Template support now, and calling out that these aren't paths but templates will make it clearer)
  > Before: `"path": "/hello_world"`
  > After: `"uriTemplate": "/hello_world{?lang}"`
- [ ] Require site (see https://github.com/thoughtworks/pacto/issues/84):
  > Before: N/A
  > After: `"site": "https://api.github.com"`
- [ ] Multiple status codes (https://github.com/thoughtworks/pacto/issues/96)
  > Before: `"status": 200`
  > After: `"status": [200, 201]`
### Additions
- [x] Add request examples (#118). These can be used for simulating consumers:
  > Before: N/A
  > After: See below
#### Example section

The examples section should contain named examples.  Each example may include:
- A request, containing headers and/or body
- A response, containing a status, headers, and/or body

This section will be used both for simulating consumers (based on the request examples) and stubbing providers (based on response examples).

Meta-validating of a contract should include confirming that all examples match the contract rules. So, for example, if a contract requires a request body, then an example request that lacks a body will cause the contract to fail meta-validation.

``` json
{
"examples": {
  "en_US": {
    "request": {
      "headers": {
        "Accept-Language": "en-US"
      }
    },
    "response": {
      "body": {
        "Hello, world!"
      }
    }
  },
  "pt_BR": {
    "request": {
      "headers": {
        "Accept-Language": "pt-BR"
      }
    },
    "response": {
      "body": {
        "Olá, Mundo!"
      }
    }
  }
}
```
