### ISSUE TITLE
CLI Roadmap

### ISSUE THREAD

**Issue by maxlinc** [thoughtworks/pacto#163]
I've started moving from [Rake->Thor](https://github.com/thoughtworks/pacto/pull/152), but I'd like to further enhance the CLI so it's easier for anyone to use pacto - both ruby devs and people uses Pacto for non-ruby projects.

I've also heard that the `pacto-server` options are confusing, and I'd like to the current Goliath-based server with a Celluloid based server in the future. Most of the options come from Goliath, so it would be a lot of work to map those options to another server.

So I'm thinking about these as new commands:
- [ ] `pacto lint [CONTRACTS]`: Validates the syntax of one or more contract files. It'll start as the equivalent of "meta_validate", with a better name, but in the future it might also give tips for improving your contracts (both style or semantics).
- [ ] `pacto proxy [CONTRACTS]`: Start a server that acts as an reverse proxy to live services so Pacto can intercept the API for validation and reporting while clients are still talking to a real service.
- [ ] `pacto stub [CONTRACTS]`: Start a server that returns stubbed responses based on the contracts.
- [ ] `pacto send [CONTRACTS]`: Sends requests based on the contracts. The default behavior will be similar to the current "validate", but I've experimented with an `--interactive` mode that lets you select from available samples and review/alter the generated data before its' sent.
